version: 1
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: automatic

handlers:
- url: /.*
  script: _go_app
  secure: optional
